#!/bin/bash
echo $@ >> /tmp/post_git.log
source `dirname $0`/.envrc

app_name=$2
mode=$4
if [ "x$mode" = "xW" -a "x$app_name" != "xgitolite-admin" ]; then
  curl -X POST $MYROKU_ADMIN_URL/application/$app_name
fi
